name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:     # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats with Private Contributions
        uses: anuraghazra/github-readme-stats@master
        with:
          username: amuyakkala
          show_icons: true
          include_all_commits: true
          count_private: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
