name: Generate GitHub Stats Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Image
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=amuyakkala&show_icons=true&count_private=true&theme=radical&include_all_commits=true&cache_seconds=1800"

      - name: Create or update auto-stats branch with stats.svg
        run: |
          git checkout --orphan auto-stats
          git reset
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add stats.svg
          git commit -m "Update GitHub stats image"
          git push -f origin auto-stats
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
